# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-ramboot"
BBFILE_PATTERN_meta-ramboot = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-ramboot = "10"

LAYERVERSION_meta-ramboot = "1"
LAYERSERIES_COMPAT_meta-ramboot = "scarthgap mickledore langdale kirkstone"

# Dependencies
LAYERDEPENDS_meta-ramboot = "core"
